export interface TVisits {
  address: string,
  apartmentsCount?: string,
  numbOfFloors?: string,
  numberOfEntrance: string,
  name: string,
  comments?: string,
  date?: string,
  shieldsOk?: string,
  shieldsNew?: string,
  shieldsReNew?: string,
  mirrorOk?: string,
  mirrorNew?: string,
  mirrorReNew?: string,
  stand?: string,
  a4?: string,
}
